### ISSUE TITLE
Move everything to parseIndexTable

### ISSUE THREAD

**Issue by zikey** [bryc/mempak#6]
~~Combine the backup checking into indexTable. Maybe use function recursively.~~ Seems to work well.
~~Also perform index checksum repair here.~~ Done
~~If implementing backup-replace, do it within parseIndexTable here.~~ Done

**Comment by bryc** [comment]
Implemented the changes. Probably more efficient now, since it doesn't call parseIndexTable for a third time. Also neater code.
