### ISSUE TITLE
Miscellaneous things 

### ISSUE THREAD

**Issue by zikey** [bryc/mempak#7]
Implement noteTable wipe in noteTableParse. Wipe all non-valid sections for cleaner files. Automatically re-order/move entries up when deleting notes?
Also perform a wipe to the unused header areas.

**Comment by bryc** [comment]
Since commit [c5068869](https://github.com/bryc/mempak/commit/c5068869c91e77ff89465571f820a63be8cb177c), `noteTable` is automatically re-ordered and wiped when deleting notes, or if there are gaps in the `noteTable`.

**Comment by bryc** [comment]
> Implement noteTable wipe in noteTableParse
> Wipe all non-valid sections for cleaner files
> Automatically re-order/move entries up when deleting notes?

This indeed was implemented in commit [c5068869]

For example:

    4E 56 38 45 35 32 00 00 82 19 00 00 00 00 00 00
    2F 22 20 22 25 1A 27 2D 1E 18 00 00 00 00 00 00
    4E 42 51 45 35 48 00 06 82 10 00 00 00 00 00 00 *
    1B 1A 2D 2D 25 1E 2D 1A 27 31 20 1A 00 00 00 00
    4E 57 57 45 35 31 00 00 02 03 00 00 00 00 00 00
    30 1A 2B 33 28 27 1E 00 00 00 00 00 00 00 00 00

Ends up becoming:

    4E 42 51 45 35 48 00 06 82 10 00 00 00 00 00 00 *
    1B 1A 2D 2D 25 1E 2D 1A 27 31 20 1A 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Certain "ghost notes" with no reference to any save data can persist in some files in the wild. MPKEdit overwrites the NoteTable with a parsed list, losing these "ghost notes".

> Also perform a wipe to the unused header areas.

This however has not been implemented, and there's no reason to do it since I don't even know what that data is or how it is used.

**Comment by bryc** [comment]
For now, the note wiping mentioned here and also in [issue 1](https://github.com/bryc/mempak/issues/1) was removed. Until a better note re-order implementation is added, there is no reason to erase any data, valid or not, in the noteTable (or anywhere else for that matter). 

The presence of ghost notes is not unlike garbage data in the index table and label areas: its existence doesn't have any real negative effect, so all will be treated the same (not doing anything with it), unless it negatively affects the data , such as invalidating it, as is the case with `8:1` bit in the note entries, or the bit in the header that makes N64 games hate the data.
